NAME	= megaphone
SRCS	= megaphone.cpp

CC		= c++
FLAGS	= -Wall -Wextra -Werror

all:		${NAME}

${NAME}:
			${CC} ${SRCS} ${FLAGS} -o ${NAME} 

fclean:	
			rm -f ${NAME}

re:			fclean all

.PHONY:		re fclean all